name: check
on:
  push:
    tags: [ v* ]
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
      - uses: actions/checkout@v3
      - name: build
        run: make
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: --timeout=3m
